### ISSUE TITLE
Improve license text so data is CC0

### ISSUE THREAD

**Issue by dpriskorn** [ErikAndreasson88/swetrails-documentation#2]
![image](https://github.com/ErikAndreasson88/swetrails-documentation/assets/68460690/e6ece8eb-3a2b-40ed-bb48-f940eee89e8d)
-> text CCBY40, data like coordinates, rooms/size, type of amenities, measures, routes close by is CC0

**Comment by dpriskorn** [comment]
även här 
![image](https://github.com/ErikAndreasson88/swetrails-documentation/assets/68460690/98678315-db73-4a1f-91e8-a27073b2c7bd)
-> CC0 för data

**Comment by ErikAndreasson88** [comment]
Fixed, changed all text to CC0. deleted all non supporting text and replaced it
