### ISSUE TITLE
License of gpx files

### ISSUE THREAD

**Issue by dpriskorn** [ErikAndreasson88/swetrails-documentation#3]
if the data is from Openstreetmap you have to license it accordingly == odbl see https://www.openstreetmap.org/copyright

If not I suggest you change the license of gpx files to CC0 so they can be imported in WD/OSM
![image](https://github.com/ErikAndreasson88/swetrails-documentation/assets/68460690/efbeb35b-9b65-48a9-8f7f-f89b3e06bf53)

**Comment by ErikAndreasson88** [comment]
Changed default license to OSM, with 1 extra option of CC0. Changed all my gps Tracked trails to OSM also.
OSM is because almost all collected data from 3rd part is in it. And because i use open street map for tiles and editing of tracks will not have a license problem.
