### ISSUE TITLE
Bugg: IDarna är inte permanenta

### ISSUE THREAD

**Issue by dpriskorn** [ErikAndreasson88/swetrails-documentation#4]
![image](https://github.com/ErikAndreasson88/swetrails-documentation/assets/68460690/a20657fb-48db-4ffd-831b-2afa62af04b6)
Det här är tyvärr inte bra alls.
Användarna ska inte kunna ändra ett id på ett objekt för då bryts länkarna tex på Wikidata.
Se https://www.wikidata.org/wiki/Q115493815 om GUPRI

**Comment by ErikAndreasson88** [comment]
Just nu så tappas inga id'n bort
ändrar du ett id och ingen annan tar det så länkar det till smma källa
detta är för googles SEO. så att man aldrig får döda länkar

Tar nån över länken så länkas det givetvis fel. skall se om det finsn ett bra sätt att hanter. Start id är autgenererat och inte alltid bra för google SEO

**Comment by salgo60** [comment]
@ErikAndreasson88  Finns ofta fördelar att ha ID:n som inte har "betydelse"

I Wikidata körs det Qnummer
* ett Qnummer som slås samman med ett annat Qnummer (händer ofta i WIkidata) så sätts [owl:SameAs](https://www.w3.org/TR/owl-ref/#sameAs-def) och det bir en redirect vid API eller web access
   * tror användargenererat data eller som i detta fall där det saknas ett ekosystem så kommer det ha skapas dubletter...
      * exempel [Svenska Riksdagsmän](https://w.wiki/6ifz) i Wikidata som slagits ihop de senaste 100 dagarna, [samma med Naturreservat](https://w.wiki/6ifn) - nota bene WD har hög ändringsfrekvens [changestream](https://wikidata-todo.toolforge.org/rcvis.html), [ljud](http://listen.hatnote.com/#en,wikidata,sv), [iphone app](https://apps.apple.com/us/app/listen-to-wikipedia/id832934300)
      
      
      [<img width="1324" alt="image" src="https://github.com/ErikAndreasson88/swetrails-documentation/assets/14206509/a23f5f1d-9a33-4e3a-b0aa-e3116cb1b431">](https://w.wiki/6ifn)

**Comment by ErikAndreasson88** [comment]
Gjort ett första steg. Tog bort användarnas möjlighet att sätta url. Den sätts nu permanent när en ny punkt skapas eller en "oediterad punkt" editeras för första gången.

**Comment by dpriskorn** [comment]
Så har alla punkterna en permanent url utan undantag?

**Comment by ErikAndreasson88** [comment]
Nej!
Just nu är alla etablerade urler fasta!
vad jag menar med det är om en bild är tillagd eller text tillagd så är de fasta:
med andra ord om nån har rörrt POI en så är de fasta. men jag hart 1000+ punkter som ligger bara med autoo placering desa är förändringsbara.

så de flesta punkter kan få ändrat namn då de inte är "skapade " / etablerade
och bara ett hundra tal punkter är skapde ;)

**Comment by dpriskorn** [comment]
Förstår inte riktigt. Är det inre enklare att bara köra genom alla i databasen och ge dem ett GUPRI?
Skit i SEO tänker jag 🤷‍♂️

**Comment by ErikAndreasson88** [comment]
SEO driver trafik och utan det så försvinner min lilla sajt. Så detta kan aldrig offras.

Men generelt så har jag ett par tusen punkter med data. Dessa är autogenererade från OSM + statens geo tjänster och andra källor
dessa har därför autogenererade id'n då dom är auto skapade.

men så fort nångon editerar en punkt blir den statisk i urlen.
med det menar jag gör första förändringen eller trycker på save första gången. För att de lagt till text eller bilder.
Så alla punkter som är intresanta för wiki data har statiska url.

men auto genererad data är teoretiskt dynamisk i urlen. Så för wikidatan och de punkter som är intresanta för det är statisk.

**Comment by dpriskorn** [comment]
Hm. Varför behöver du SEO? Vad är din business modell?

**Comment by salgo60** [comment]
Kan man inte utnyttja Wikidata att dra trafik till siten? Skapa en Wikidata egenskap och se om det gör skillnad?

**Comment by ErikAndreasson88** [comment]
Wikidata kan inte dra trafik då den inte är SEO vänlig.
Men har skrivit om systemet så att URL är nu permanenta fullständigt, efter en punkt skapats.

**Comment by salgo60** [comment]
@ErikAndreasson88 hur tänker du?

Kolla i denna [tweet](https://twitter.com/salgo60/status/1512323184401555457?s=20) där Google ligger och läser [Wikidatas changestream](https://wikidata-todo.toolforge.org/rcvis.html)

<img width="655" alt="image" src="https://github.com/ErikAndreasson88/swetrails-documentation/assets/14206509/75aa8cee-4af4-4e4b-bbed-f7d4f70833c2">

1. där har Google läst [WIkidata change stream](https://wikidata-todo.toolforge.org/rcvis.html)
2. hämtat ut koordinaten för [Älvrosgården](https://www.wikidata.org/wiki/Q56573825?uselang=sv) från Wikidata - [graf](https://w.wiki/NAg)
3. **20 minuter senare då jag testa** söka hade dom från att innan bara varit en "text" sökning "älvrosgården"
    1. gjort en "infobox" till höger med koordinat
    2. kopplat det till en post i deras [Kunskapsgraf](https://www.youtube.com/watch?v=mmQl6VGvX-c) = [kgmid=/g/11fctqy99z](https://www.google.com/search?kgmid=/g/11fctqy99z)
    3. hämtat bilder dom har tagna vid den koordinaten o ch lagt in det i "infoboxen"
    4. fångat upp recensioner....
    5. kopplat det till plats Skansen
    
Wikidata används av massa olika företag se artikel Wired "[Inside the Alexa-Friendly World of Wikidata](https://www.wired.com/story/inside-the-alexa-friendly-world-of-wikidata/)" så att synas där tror vi påverkar din plats i SEO hierarkin...

**Comment by dpriskorn** [comment]
Verkar fixat nu, när jag testade redigera https://swetrails.com/sv/route/Bergslagsleden var id-n stabil efter namnbyte. Kanon!

**Comment by ErikAndreasson88** [comment]
Jepp har låst ner alla id till orginal id eller genererat id vi första skapning av punkt/rutt.
